GET https://api.github.com/users/jasonicarter HTTP/1.1

###
GET http://localhost:8080/admin/metrics

###
# Chirp is too long
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "This is an opinion I need to share with the world is this any longer that it should be? what about now, I'm sure this is waaaaaaaya tooo long for a chirpy to handle isn't"
}

###
# Something went wrong
POST http://localhost:8080/api/validate_chirp
Content-Type: application/json


  "body": "This is an opinion I need to share with the world"
}

###
POST http://localhost:8080/api/chirps
Content-Type:  application/json

{
  "body": "Hello, world!",
  "user_id": "3b76d233-b14e-4a61-a56d-bfd5204dc7cb"
}

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "password": "04234",
  "email": "lane@example.com"
}

###
POST http://localhost:8080/admin/reset

###
GET http://localhost:8080/api/chirps/3b76d233-b14e-4a61-a56d-bfd5204dc7cb
Content-Type:  application/json